import { Asset, Customer } from "@/type/index.type";

export const data: Asset[] =
    [
        {
            id: "1",
            "code": "784/S1",
            "category": "A",
            "width": "40",
            "height": "40",
            "unit": "1",
            "total_area": "1600 SQRT",
            "zone": "WEH",
            "area": "VILE PARLE",
            location: "ON WEH, NR. AIRPORT (2106X2106)",
            media_type: "BILLBOARD",
            "screen_type": "LED",
            "facing": "",
            "zipcode": "",
            "city": "MUMBAI",
            "country": "INDIA",
            "state": "MAHARASHTRA",
            "description": "",
            "remark": ""
        },
        {
            id: "2",
            "code": "51/S1",
            "category": "A",
            "width": "20",
            "height": "20",
            "unit": "1",
            "total_area": "400 SQRT",
            "zone": "CENTRAL",
            "area": "KING CIRCLE",
            location: "ON EEH, BF. SION CIRCLE (972X972)",
            media_type: "BILLBOARD",
            "screen_type": "LED",
            "facing": "",
            "zipcode": "",
            "city": "MUMBAI",
            "country": "INDIA",
            "state": "MAHARASHTRA",
            "description": "",
            "remark": ""
        },
        {
            id: "3",
            "code": "60/S1",
            "category": "A",
            "width": "40",
            "height": "40",
            "unit": "1",
            "total_area": "1600 SQRT",
            "zone": "WEH",
            "area": "SANTACRUZ",
            location: "ON WEH, ON VAKOLA FLYOVER (2106X2106)",
            media_type: "BILLBOARD",
            "screen_type": "LED",
            "facing": "",
            "zipcode": "",
            "city": "MUMBAI",
            "country": "INDIA",
            "state": "MAHARASHTRA",
            "description": "",
            "remark": ""
        },
        {
            id: "4",
            "code": "56/S1",
            "category": "A",
            "width": "20",
            "height": "20",
            "unit": "1",
            "total_area": "400 SQRT",
            "zone": "TOWN",
            "area": "LOWER PAREL",
            location: "OPP. PALLADIUM MALL (DN) (972X972)",
            media_type: "BILLBOARD",
            "screen_type": "LED",
            "facing": "",
            "zipcode": "",
            "city": "MUMBAI",
            "country": "INDIA",
            "state": "MAHARASHTRA",
            "description": "",
            "remark": ""
        },
        {
            id: "4",
            "code": "56/S1",
            "category": "A",
            "width": "20",
            "height": "20",
            "unit": "1",
            "total_area": "400 SQRT",
            "zone": "TOWN",
            "area": "LOWER PAREL",
            location: "OPP. PALLADIUM MALL (DN) (972X972)",
            media_type: "BILLBOARD",
            "screen_type": "LED",
            "facing": "",
            "zipcode": "",
            "city": "MUMBAI",
            "country": "INDIA",
            "state": "MAHARASHTRA",
            "description": "",
            "remark": ""
        },
    ]

export const customers: Customer[] = [
    {
        id: "1",
        name: "Hitesh Solanki",
        email: "hiteshsolanki4623@gmail.com",
        phone: "+919004713782",
        address: "B/710, Riddhi Siddhi Apt",

        tags: ["Tech", "health-care"],

        city: "Mumbai",
        country: "India",
        state: "Maharashtra",
        company_name: "Solanki's",
        company_domain: "solanki.com",
        company_info: "World Best Company with the largest target Audience"
    },
    {
        id: "2",
        name: "Niraj Solanki",
        email: "nirajsolanki729@gmail.com",
        phone: "+919930032332",
        address: "B/710, Riddhi Siddhi Apt",

        tags: ["CA", "health-care"],

        city: "Mumbai",
        country: "India",
        state: "Maharashtra",
        company_name: "Solanki's",
        company_domain: "solanki.com",
        company_info: "World Best Company with the largest target Audience"
    }
]